#!/bin/sh

NOTES="$HOME/.local/share/notes"

TOOLS="fzf glow deno rclone"

for tool in $TOOLS; do
  which $tool > /dev/null 2>&1 || {
    echo "$tool not found"
    exit 1
  }
done

function selectFile() {
  find $NOTES -name "*.md" | tac | while IFS= read -r filePath; do
      cat "$filePath" | tr "\n" " "
      printf ":"
      printf "$filePath" | sed "s|^$NOTES/||"
      printf "\n"
    done | fzf \
        --style minimal \
        --reverse \
        --delimiter ":" \
        --preview \
        "CLICOLOR_FORCE=1 COLORTERM=truecolor glow --style dark $NOTES/\$(echo {} | rev | cut -d ':' -f1 | rev)" |\
        rev | cut -d ":" -f1 | rev
}

function checkBrokenLinks() {
    find $NOTES -name "*.md" | while IFS= read -r filePath; do
        # Get all links in the current file
        grep -o '\[\[[^]]*\]\]' "$filePath" | while IFS= read -r link; do
            # Extract the link text (remove [[ and ]] and any pipe part)
            linkText=$(echo "$link" | sed -E 's/\[\[([^|]*)(\|[^]]*)?\]\]/\1/')
            # Check if the linked file exists
            if [ ! -f "$NOTES/$linkText.md" ]; then
                printf "Broken link '%s' in file: %s\n" "$linkText" "$(echo "$filePath" | sed "s|^$NOTES/||")"
            fi
        done
    done
}

function syncNotes() {
  rclone sync $NOTES MEGA:NOTES --progress --ignore-times --quiet --stats=0 > /dev/null 2>&1 &
}

function endRun() {
    echo "Ending run"
    fmt="$(deno fmt --line-width 80 $NOTES 2>&1)"
    if [ $? -ne 0 ]; then
        echo "$fmt"
    fi
    checkBrokenLinks
    syncNotes
}

function helpText() {
    printf "Usage: notes [c|r|u|d]\n"
    printf "  c: Create a new note\n"
    printf "  r: Read a note\n"
    printf "  u: Update a note\n"
    printf "  d: Delete a note\n"
}

if [ $# -gt 1 ]; then
    helpText
    endRun
    exit 0
fi


if [ "$1" = "c" ]; then
    filenameID=$(date +%Y%m%d%H%M%S%N)
    printf "# %s\n\n" "$filenameID" > "$NOTES/$filenameID.md"
    nvim "$NOTES/$filenameID.md"
    endRun
    exit 0
fi

if [ "$1" = "r" ]; then
    selectedFile=$(selectFile)
    if [ -z "$selectedFile" ]; then
        printf "No file selected\n"
        endRun
        exit 1
    else
        glow "$NOTES/$selectedFile"
    fi
    endRun
    exit 0
fi

if [ "$1" = "u" ]; then
    selectedFile=$(selectFile)
    if [ -z "$selectedFile" ]; then
        printf "No file selected\n"
        endRun
        exit 1
    else
        nvim "$NOTES/$selectedFile"
    fi
    endRun
    exit 0
fi

if [ "$1" = "d" ]; then
    selectedFile=$(selectFile)
    if [ -z "$selectedFile" ]; then
        printf "No file selected\n"
    else
        printf "Are you sure you want to delete $selectedFile? (y/n): "
        read -r confirm
        if [ "$confirm" = "y" ]; then
            rm "$NOTES/$selectedFile"
            printf "File deleted\n"
        else
            printf "File not deleted\n"
        fi
    fi
    endRun
    exit 0
fi


helpText

endRun
exit 0