#!/usr/bin/env sh

[ "$(zellij action list-panes --all | grep -F ".config/zellij/control-panel" | wc -l)" -gt 1 ] && exit 0

control_command=$(
    printf "# TAB:NEW\n# FZF\n# CREATE NEW SESSION\n# DETACH\n# SCROLL\n# CLOSE\n%s" "$(zellij list-sessions --short | sed "s/^/SESSION:/")" | sort -f 2>/dev/null |
    gum filter --placeholder "Search..." --no-show-help --indicator ">" --indicator.foreground "#FFF"
)

[ -z "$control_command" ] && exit 0

if [ "$control_command" = "# TAB:NEW" ]; then
    zellij action new-pane --tab-id 0
    exit 0
fi

if [ "$control_command" = "# SCROLL" ]; then
    zellij action switch-mode scroll
    exit 0
fi

if [ "$control_command" = "# CLOSE" ]; then
    exit 0
fi

if [ "$control_command" = "# FZF" ]; then
    zellij action write-chars "$(fzf --walker "file,dir,follow,hidden")" -p 0
    exit 0
fi

if [ "$control_command" = "# DETACH" ]; then
    zellij action detach
    exit 0
fi

if [ "$control_command" = "# CREATE NEW SESSION" ]; then
    control_command=$(gum input --cursor.foreground "#FFF" --placeholder "Enter new session name..." --no-show-help)
    [ -z "$control_command" ] && exit 0
    control_command="SESSION:$control_command"
fi

case "$control_command" in
    SESSION:*)
        if printf "%s" "${control_command#SESSION:}" | grep -Eq "^[A-Za-z][A-Za-z0-9]{0,14}$"; then
	    zellij action switch-session $(printf "%s" "${control_command#SESSION:}")
            exit 0
        fi
        ;;
esac

gum style --align center --width $(tput cols) "Invalid session name. Use 1-15 alphanumeric characters, starting with a letter."
sleep 5
exit 1
