vim.diagnostic.config({ update_in_insert = true })

-- require("main.lspconfig-list.deno")
require("main.lspconfig-list.go")
require("main.lspconfig-list.lua")
require("main.lspconfig-list.texlab")
require("main.lspconfig-list.marksman")
-- require("main.lspconfig-list.css_variables")
-- require("main.lspconfig-list.cssls")
require("main.lspconfig-list.ts_ls")
require("main.lspconfig-list.zig")
