source "$(dirname "${BASH_SOURCE[0]}")/path"
source "$(dirname "${BASH_SOURCE[0]}")/ps"
source "$(dirname "${BASH_SOURCE[0]}")/alias"
source "$(dirname "${BASH_SOURCE[0]}")/fzf"

which gpgconf > /dev/null && export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"

export EDITOR="nvim"
